name = "me-offer"
compatibility_date = "2025-04-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "meoffer-gaokao"
database_id = "abee2971-12f2-4f09-8c86-8ce1ce604a7b"
