-- Me Offer · 31 省配置初始化
-- Source: data_raw/knowledge/provinces_rules_2025.json

DELETE FROM provinces;

INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('shandong', '山东省', '山东', 2020, '3+3', '专业+院校', '[{"batch": "普通类常规批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}, {"batch": "提前批", "volunteer_count": 2, "unit": "有序志愿", "parallel": false}, {"batch": "艺术类", "volunteer_count": 60, "unit": "专业+学校", "parallel": true}]', 24, 48, 24, '6 选 3（物/化/生/政/史/地）', '["位次优先 · 遵循志愿 · 一轮投档", "不服从调剂可能滑档，建议全部填满", "专业组内不存在调剂（每个志愿=独立专业）"]', 'complete', 1);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('hebei', '河北省', '河北', 2021, '3+1+2', '专业+院校', '[{"batch": "本科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}, {"batch": "提前批", "volunteer_count": 10, "unit": "专业+学校", "parallel": true}]', 24, 48, 24, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["与山东同模式 · 扩展成本最低"]', 'pending', 2);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('liaoning', '辽宁省', '辽宁', 2021, '3+1+2', '专业+院校', '[{"batch": "本科批", "volunteer_count": 112, "unit": "专业+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 60, "unit": "专业+学校", "parallel": true}, {"batch": "本科提前批", "volunteer_count": 2, "unit": "有序+4 个专业", "parallel": false}]', 28, 56, 28, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["全国志愿数最多省（112 个），填报需更精细"]', 'pending', 2);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('chongqing', '重庆市', '重庆', 2021, '3+1+2', '专业+院校', '[{"batch": "本科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}]', 24, 48, 24, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["直辖市 · 西南地区高考重镇"]', 'pending', 3);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('qinghai', '青海省', '青海', 2025, '3+1+2', '专业+院校', '[{"batch": "本科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 96, "unit": "专业+学校", "parallel": true}]', 24, 48, 24, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["2025 新高考改革首年"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('tianjin', '天津市', '天津', 2020, '3+3', '专业+院校', '[{"batch": "本科批", "volunteer_count": 96, "unit": "专业(类)+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 96, "unit": "专业(类)+学校", "parallel": true}]', 24, 48, 24, '6 选 3', '["直辖市 · 与山东同模式"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('zhejiang', '浙江省', '浙江', 2017, '3+3', '专业+院校', '[{"batch": "普通类第一段", "volunteer_count": 80, "unit": "专业+学校", "parallel": true, "note": "分 3 段录取"}, {"batch": "普通类第二段", "volunteer_count": 80, "unit": "专业+学校", "parallel": true}, {"batch": "普通类第三段", "volunteer_count": 80, "unit": "专业+学校", "parallel": true}]', 20, 40, 20, '7 选 3（含技术）', '["分 3 段填报 · 每段都有录取机会", "选考 7 选 3 含技术科目"]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('hainan', '海南省', '海南', 2020, '3+3', '专业+院校', '[{"batch": "本科批", "volunteer_count": 80, "unit": "专业(类)+学校", "parallel": true}, {"batch": "专科批", "volunteer_count": 60, "unit": "专业(类)+学校", "parallel": true}]', 20, 40, 20, '6 选 3', '["赋分特色"]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('guangdong', '广东省', '广东', 2021, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组 × 6 专业+调剂", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组 × 6 专业+调剂", "parallel": true}, {"batch": "提前批", "volunteer_count": 8, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["每组内 6 个专业 + 是否服从调剂", "组内会调剂到不想去的专业，建议勾选服从", "一所大学可能有多个专业组（选科要求不同）"]', 'pending', 3);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('jiangsu', '江苏省', '江苏', 2021, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组 × 6 专业+调剂", "parallel": true}, {"batch": "专科批", "volunteer_count": 40, "unit": "院校专业组 × 6 专业+调剂", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["教育大省 · 高分段竞争激烈"]', 'pending', 3);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('fujian', '福建省', '福建', 2021, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('hubei', '湖北省', '湖北', 2021, '3+1+2', '院校专业组', '[{"batch": "本科普通批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["武汉高校集群"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('hunan', '湖南省', '湖南', 2021, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('jiangxi', '江西省', '江西', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('guangxi', '广西壮族自治区', '广西', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('guizhou', '贵州省', '贵州', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('anhui', '安徽省', '安徽', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('gansu', '甘肃省', '甘肃', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('sichuan', '四川省', '四川', 2025, '3+1+2', '院校专业组', '[{"batch": "本科批 A 段", "volunteer_count": 20, "unit": "院校专业组", "parallel": true}, {"batch": "本科批 B 段", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["分 A/B 段 · 不同位次考生区分"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('shaanxi', '陕西省', '陕西', 2025, '3+1+2', '院校专业组', '[{"batch": "本科提前批 B 段", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["2025 新高考首年 · 西安高校集群"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('shanxi', '山西省', '山西', 2025, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('yunnan', '云南省', '云南', 2025, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('beijing', '北京市', '北京', 2020, '3+3', '院校专业组', '[{"batch": "本科普通批", "volunteer_count": 30, "unit": "院校专业组", "parallel": true}, {"batch": "专科普通批", "volunteer_count": 20, "unit": "学校 × 1 专业", "parallel": true}]', 8, 15, 7, '6 选 3', '["首都 · 志愿数相对少 · 竞争激烈"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('shanghai', '上海市', '上海', 2017, '3+3', '院校专业组', '[{"batch": "本科提前批", "volunteer_count": 20, "unit": "院校专业组", "parallel": false}, {"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组 × 6 专业+调剂", "parallel": true}, {"batch": "专科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '6 选 3', '["首批改革省 · 新高考发源地之一"]', 'pending', 4);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('henan', '河南省', '河南', 2025, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 48, "unit": "院校专业组", "parallel": true}, {"batch": "专科批", "volunteer_count": 48, "unit": "院校专业组", "parallel": true}]', 12, 24, 12, '物/历 2 选 1 + 化/生/政/地 4 选 2', '["2025 新高考首年 · 全国考生最多省（百万+）"]', 'pending', 2);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('jilin', '吉林省', '吉林', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('heilongjiang', '黑龙江省', '黑龙江', 2024, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 40, "unit": "院校专业组", "parallel": true}]', 10, 20, 10, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('neimenggu', '内蒙古自治区', '内蒙古', NULL, '传统文理', '院校志愿', '[{"batch": "本科一批", "volunteer_count": 6, "unit": "院校+6专业", "parallel": true, "note": "动态排名"}, {"batch": "本科二批", "volunteer_count": 10, "unit": "院校+6专业", "parallel": true}, {"batch": "专科批", "volunteer_count": 10, "unit": "院校+6专业", "parallel": true}]', NULL, NULL, NULL, '文理分科', '["唯一保留传统文理分科", "动态排名 · 特色投档"]', 'not_supported', 9);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('xinjiang', '新疆维吾尔自治区', '新疆', NULL, '传统文理', '院校志愿', '[{"batch": "本科一批", "volunteer_count": 9, "unit": "院校+6专业", "parallel": true}, {"batch": "本科二批", "volunteer_count": 12, "unit": "院校+6专业", "parallel": true}]', NULL, NULL, NULL, '文理分科', '["暂未改革 · 双语教学特殊政策"]', 'not_supported', 9);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('xizang', '西藏自治区', '西藏', NULL, '传统文理', '院校志愿', '[{"batch": "本科批", "volunteer_count": 10, "unit": "院校+6专业", "parallel": true}]', NULL, NULL, NULL, '文理分科', '["民族特色加分 · 少数民族单列"]', 'not_supported', 9);
INSERT INTO provinces (code, name, name_short, reform_year, reform_type, model, batches_json, chong_count, wen_count, bao_count, subject_select, special_notes, data_status, recommended_priority) VALUES ('ningxia', '宁夏回族自治区', '宁夏', 2025, '3+1+2', '院校专业组', '[{"batch": "本科批", "volunteer_count": 45, "unit": "院校专业组", "parallel": true}]', 12, 22, 11, '物/历 2 选 1 + 化/生/政/地 4 选 2', '[]', 'pending', 5);
